version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Amman'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      npm:
        patterns: ['*']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Amman'
    commit-message:
      prefix: 'chore(deps-ga)'
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
      timezone: 'Asia/Amman'
    commit-message:
      prefix: 'chore(deps)'
    groups:
      composer:
        patterns: ['*']
